// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6nqWCHOAqDUe5QRn5CSBQ30NaJeutOHo',
    appId: '1:926962689523:web:a77cb9e604760e9254de86',
    messagingSenderId: '926962689523',
    projectId: 'taskcsc-4cad0',
    authDomain: 'taskcsc-4cad0.firebaseapp.com',
    storageBucket: 'taskcsc-4cad0.firebasestorage.app',
    measurementId: 'G-QEGPC08SSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_77WTgI3tRzeq6qz-kD1AZB_7sJ5EtY',
    appId: '1:926962689523:android:c005a8687c1741f454de86',
    messagingSenderId: '926962689523',
    projectId: 'taskcsc-4cad0',
    storageBucket: 'taskcsc-4cad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIFudb4Ksa49mOZXhZmdK7g42l5V9NVUk',
    appId: '1:926962689523:ios:55a480479b42103d54de86',
    messagingSenderId: '926962689523',
    projectId: 'taskcsc-4cad0',
    storageBucket: 'taskcsc-4cad0.firebasestorage.app',
    iosBundleId: 'com.example.taskcsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIFudb4Ksa49mOZXhZmdK7g42l5V9NVUk',
    appId: '1:926962689523:ios:55a480479b42103d54de86',
    messagingSenderId: '926962689523',
    projectId: 'taskcsc-4cad0',
    storageBucket: 'taskcsc-4cad0.firebasestorage.app',
    iosBundleId: 'com.example.taskcsc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6nqWCHOAqDUe5QRn5CSBQ30NaJeutOHo',
    appId: '1:926962689523:web:09f2314baff8b3ac54de86',
    messagingSenderId: '926962689523',
    projectId: 'taskcsc-4cad0',
    authDomain: 'taskcsc-4cad0.firebaseapp.com',
    storageBucket: 'taskcsc-4cad0.firebasestorage.app',
    measurementId: 'G-E0FT4FX3TN',
  );
}
